
 drop table if exists address;
 drop table if exists location;
 drop table if exists order_detail;
 drop table if exists orders;
 drop table if exists product;
 drop table if exists product_category;
 drop table if exists revenue;
 drop table if exists roles;
 drop table if exists stock;
 drop table if exists user;
 create table address (address_id integer not null auto_increment, city varchar(255), country varchar(255), county varchar(255), street_address varchar(255), primary key (address_id)) engine=InnoDB;
 create table location (location_id integer not null auto_increment, name varchar(255), location_address_address_id integer, primary key (location_id)) engine=InnoDB;
 create table order_detail (id integer not null auto_increment, product_id integer, quantity integer not null, orders_order_id integer, primary key (id)) engine=InnoDB;
 create table orders (order_id integer not null auto_increment, created_at datetime, customer_user_id integer, delivery_address_location_id integer, shipped_from_location_id integer, primary key (order_id)) engine=InnoDB;
 create table product (product_id integer not null auto_increment, description varchar(255), image_url varchar(255), name varchar(255), price decimal(19,2), weight double precision not null, category_category_id integer, primary key (product_id)) engine=InnoD;
 create table product_category (category_id integer not null auto_increment, description varchar(255), name varchar(255), primary key (category_id)) engine=InnoDB;
 create table revenue (revenue_id integer not null auto_increment, date date, sum decimal(19,2), location_location_id integer, primary key (revenue_id)) engine=InnoDB;
 create table roles (role_id integer not null auto_increment, name varchar(255), primary key (role_id)) engine=InnoDB;
 create table stock (stock_id integer not null auto_increment, quantity integer not null, location_location_id integer, product_product_id integer, primary key (stock_id)) engine=InnoDB;
 create table user (user_id integer not null auto_increment, email_address varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), username varchar(255), role_role_id integer, primary key (user_id)) engine=InnoDB;
 alter table location add constraint FKblv7ytjhl8fr2n41kqed7ontt foreign key (location_address_address_id) references address (address_id);
 alter table order_detail add constraint FKk9rcebabetm8w5xfbtk7fd1go foreign key (orders_order_id) references orders (order_id);
 alter table orders add constraint FK8fvgue6769ma18to0aiv8f54s foreign key (customer_user_id) references user (user_id);
 alter table orders add constraint FK8hqty341rl663gmoici7jrjfb foreign key (delivery_address_location_id) references location (location_id);
 alter table orders add constraint FKjgk8fk0w119k8u9xh4cpmnfbo foreign key (shipped_from_location_id) references location (location_id);
 alter table product add constraint FK6juixr1i4xf0wo3jo281hd44w foreign key (category_category_id) references product_category (category_id);
 alter table revenue add constraint FKiai6taqijuuthl87orkya7hc6 foreign key (location_location_id) references location (location_id);
 alter table stock add constraint FKdpqqcvx5b9mlkyduslfqb8i1t foreign key (location_location_id) references location (location_id);
 alter table stock add constraint FKrwdkwjf037066qtbpq0pg0h6n foreign key (product_product_id) references product (product_id);
 alter table user add constraint FK4keqlw3ucfmfsbeu8r1ijdppf foreign key (role_role_id) references roles (role_id);
